M48
; DRILL file {KiCad 9.0.0} date 2025-04-01T16:17:15+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-01T16:17:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X34.0Y-41.0
X34.0Y-56.0
X76.0Y-41.0
X76.0Y-56.0
M30
