M48
; DRILL file {KiCad 9.0.0} date 2025-04-02T21:11:51+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-02T21:11:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X66.0Y-55.0
X66.0Y-70.0
X108.0Y-55.0
X108.0Y-70.0
M30
